# In config-repo/service-b/application-prod.yml
service:
  name: "Service B Production Environment" # 서비스 설명 (선택 사항)
  student_id: "여기에_본인_학번을_입력하세요"   # 미션 요구사항
  student_name: "여기에_본인_이름을_입력하세요" # 미션 요구사항
logging:
  level:
    root: WARN
